import type {
  Article,
  Award,
  InnovationPractice,
  Job,
  Office,
  Person,
  Project,
  Service,
  SiteConfig,
  Testimonial,
} from "@/types/content";

const img = (slug: string, alt: string, aspect: "16:9" | "4:3" | "3:4") => ({
  src: `/media/${slug}.svg`,
  alt,
  aspect,
});

const seo = (title: string, description: string) => ({ title, description });

export const siteConfig: SiteConfig = {
  id: "site-001",
  slug: "north-axis-studio",
  title: "North Axis Studio",
  summary:
    "Global design and consulting studio focused on strategic clarity, premium digital experiences, and transformation delivery.",
  seo: seo(
    "North Axis Studio | Global Design and Consulting",
    "North Axis Studio partners with organizations to design strategy, digital products, and growth pathways.",
  ),
  heroMedia: img(
    "hero-atrium",
    "Abstract atrium with warm editorial lighting",
    "16:9",
  ),
  tags: ["global", "design", "consulting"],
  taxonomies: {
    market: ["B2B", "B2C"],
    capability: ["Design", "Consulting", "Innovation"],
  },
  relatedIds: {
    offices: ["office-nyc", "office-cph", "office-sin"],
    services: ["service-brand-architecture", "service-transformation-roadmaps"],
  },
  studioName: "North Axis Studio",
  email: "hello@northaxis.studio",
  mainNavigation: [
    { label: "Projects", to: "/projects" },
    { label: "Services", to: "/services" },
    { label: "Research & Innovation", to: "/research-innovation" },
    { label: "People", to: "/people" },
    { label: "News", to: "/news" },
    { label: "Awards", to: "/awards" },
    { label: "Careers", to: "/careers" },
    { label: "Contact", to: "/contact" },
  ],
  featuredPathways: [
    { label: "Design", to: "/services/design" },
    { label: "Consulting", to: "/services/consulting" },
  ],
  legalNavigation: [
    { label: "Terms", to: "/terms" },
    { label: "Privacy", to: "/privacy" },
  ],
};

export const offices: Office[] = [
  {
    id: "office-nyc",
    slug: "new-york",
    title: "New York Studio",
    summary:
      "Commercial strategy and digital design hub for North American engagements.",
    seo: seo(
      "New York Studio | North Axis",
      "North Axis Studio office in New York.",
    ),
    heroMedia: img("office-new-york", "Editorial skyline composition", "16:9"),
    tags: ["americas", "commercial", "product"],
    taxonomies: { region: ["Americas"], capability: ["Strategy", "Product"] },
    relatedIds: {
      people: ["person-amina", "person-julian"],
      projects: ["project-orbit-rail"],
    },
    city: "New York",
    country: "USA",
    region: "Americas",
    addressLine: "11 Mercer Street, Manhattan",
  },
  {
    id: "office-cph",
    slug: "copenhagen",
    title: "Copenhagen Studio",
    summary:
      "Service design and systems-thinking center for public and enterprise programs.",
    seo: seo(
      "Copenhagen Studio | North Axis",
      "North Axis Studio office in Copenhagen.",
    ),
    heroMedia: img("office-copenhagen", "Nordic editorial workspace", "16:9"),
    tags: ["emea", "service-design", "systems"],
    taxonomies: {
      region: ["EMEA"],
      capability: ["Service Design", "Research"],
    },
    relatedIds: {
      people: ["person-soren", "person-lina"],
      projects: ["project-civic-grid"],
    },
    city: "Copenhagen",
    country: "Denmark",
    region: "EMEA",
    addressLine: "47 Vestergade, Copenhagen K",
  },
  {
    id: "office-singapore",
    slug: "singapore",
    title: "Singapore Studio",
    summary:
      "Regional transformation and growth studio serving APAC operators.",
    seo: seo(
      "Singapore Studio | North Axis",
      "North Axis Studio office in Singapore.",
    ),
    heroMedia: img(
      "office-singapore",
      "Contemporary tower reflections",
      "16:9",
    ),
    tags: ["apac", "growth", "transformation"],
    taxonomies: {
      region: ["APAC"],
      capability: ["Transformation", "Analytics"],
    },
    relatedIds: {
      people: ["person-nadia", "person-kenji"],
      projects: ["project-monsoon-loop"],
    },
    city: "Singapore",
    country: "Singapore",
    region: "APAC",
    addressLine: "8 Robinson Road",
  },
  {
    id: "office-nairobi",
    slug: "nairobi",
    title: "Nairobi Studio",
    summary: "Inclusive product and service innovation for growth markets.",
    seo: seo(
      "Nairobi Studio | North Axis",
      "North Axis Studio office in Nairobi.",
    ),
    heroMedia: img("office-nairobi", "Urban morning light scene", "16:9"),
    tags: ["emea", "innovation", "inclusive"],
    taxonomies: { region: ["EMEA"], capability: ["Innovation", "Service"] },
    relatedIds: { people: ["person-kofi"], projects: ["project-rural-signal"] },
    city: "Nairobi",
    country: "Kenya",
    region: "EMEA",
    addressLine: "3 Riverside Drive",
  },
  {
    id: "office-london",
    slug: "london",
    title: "London Studio",
    summary:
      "Brand architecture and communications strategy for global organizations.",
    seo: seo(
      "London Studio | North Axis",
      "North Axis Studio office in London.",
    ),
    heroMedia: img("office-london", "Minimal architectural facade", "16:9"),
    tags: ["emea", "brand", "communications"],
    taxonomies: { region: ["EMEA"], capability: ["Brand", "Narrative"] },
    relatedIds: { people: ["person-elena"], projects: ["project-aurora-grid"] },
    city: "London",
    country: "UK",
    region: "EMEA",
    addressLine: "21 Clerkenwell Road",
  },
  {
    id: "office-toronto",
    slug: "toronto",
    title: "Toronto Studio",
    summary: "Data-led service modernization and policy design practice.",
    seo: seo(
      "Toronto Studio | North Axis",
      "North Axis Studio office in Toronto.",
    ),
    heroMedia: img("office-toronto", "Editorial downtown vista", "16:9"),
    tags: ["americas", "policy", "analytics"],
    taxonomies: { region: ["Americas"], capability: ["Policy", "Data"] },
    relatedIds: { people: ["person-dev"], projects: ["project-atlas-travel"] },
    city: "Toronto",
    country: "Canada",
    region: "Americas",
    addressLine: "145 Wellington Street West",
  },
  {
    id: "office-sao-paulo",
    slug: "sao-paulo",
    title: "Sao Paulo Studio",
    summary:
      "Market expansion and CX design studio for Latin American growth programs.",
    seo: seo(
      "Sao Paulo Studio | North Axis",
      "North Axis Studio office in Sao Paulo.",
    ),
    heroMedia: img("office-sao-paulo", "Concrete and glass forms", "16:9"),
    tags: ["americas", "cx", "expansion"],
    taxonomies: { region: ["Americas"], capability: ["CX", "Growth"] },
    relatedIds: {
      people: ["person-maya"],
      projects: ["project-verde-finance"],
    },
    city: "Sao Paulo",
    country: "Brazil",
    region: "Americas",
    addressLine: "118 Avenida Paulista",
  },
];

export const services: Service[] = [
  {
    id: "service-brand-architecture",
    slug: "brand-architecture",
    title: "Brand Architecture",
    summary:
      "Portfolio and proposition architecture for diversified organizations.",
    seo: seo(
      "Brand Architecture Service",
      "Clarify portfolio and proposition strategy.",
    ),
    heroMedia: img("service-brand-architecture", "Layered brand blocks", "4:3"),
    tags: ["brand", "strategy"],
    taxonomies: { group: ["design"], stage: ["strategy"] },
    relatedIds: {
      projects: ["project-aurora-grid", "project-lumen-care"],
      people: ["person-elena"],
    },
    group: "design",
    deliveryMode: "engagement",
  },
  {
    id: "service-identity-systems",
    slug: "identity-systems",
    title: "Identity Systems",
    summary: "Scalable visual and verbal systems for digital-first ecosystems.",
    seo: seo("Identity Systems Service", "Build coherent identity systems."),
    heroMedia: img(
      "service-identity-systems",
      "Typographic editorial panel",
      "4:3",
    ),
    tags: ["identity", "design"],
    taxonomies: { group: ["design"], stage: ["design"] },
    relatedIds: {
      projects: ["project-atlas-travel", "project-orbit-rail"],
      people: ["person-lina"],
    },
    group: "design",
    deliveryMode: "engagement",
  },
  {
    id: "service-experience-design",
    slug: "experience-design",
    title: "Experience Design",
    summary:
      "Journey-level experience design across service and product touchpoints.",
    seo: seo(
      "Experience Design Service",
      "Design connected customer journeys.",
    ),
    heroMedia: img(
      "service-experience-design",
      "Flowing pathway visual",
      "4:3",
    ),
    tags: ["ux", "journeys"],
    taxonomies: { group: ["design"], stage: ["delivery"] },
    relatedIds: {
      projects: ["project-northshore-health"],
      people: ["person-julian"],
    },
    group: "design",
    deliveryMode: "program",
  },
  {
    id: "service-design-ops",
    slug: "design-operations",
    title: "Design Operations",
    summary: "Operating models and governance for enterprise design maturity.",
    seo: seo(
      "Design Operations Service",
      "Scale design with systems and governance.",
    ),
    heroMedia: img(
      "service-design-operations",
      "Grid and governance motif",
      "4:3",
    ),
    tags: ["operations", "scale"],
    taxonomies: { group: ["design"], stage: ["enablement"] },
    relatedIds: { projects: ["project-civic-grid"], people: ["person-soren"] },
    group: "design",
    deliveryMode: "advisory",
  },
  {
    id: "service-content-design",
    slug: "content-design",
    title: "Content Design",
    summary:
      "Editorial frameworks and UX writing systems for product ecosystems.",
    seo: seo(
      "Content Design Service",
      "Shape coherent editorial product language.",
    ),
    heroMedia: img("service-content-design", "Editorial cards and type", "4:3"),
    tags: ["content", "ux-writing"],
    taxonomies: { group: ["design"], stage: ["delivery"] },
    relatedIds: { articles: ["article-clarity-cost"], people: ["person-maya"] },
    group: "design",
    deliveryMode: "engagement",
  },
  {
    id: "service-transformation-roadmaps",
    slug: "transformation-roadmaps",
    title: "Transformation Roadmaps",
    summary:
      "Cross-functional roadmaps connecting strategy to execution milestones.",
    seo: seo(
      "Transformation Roadmaps Service",
      "Plan enterprise transformation with confidence.",
    ),
    heroMedia: img("service-transformation-roadmaps", "Roadmap lanes", "4:3"),
    tags: ["transformation", "strategy"],
    taxonomies: { group: ["consulting"], stage: ["strategy"] },
    relatedIds: {
      projects: ["project-monsoon-loop", "project-verde-finance"],
      people: ["person-nadia"],
    },
    group: "consulting",
    deliveryMode: "advisory",
  },
  {
    id: "service-service-portfolio",
    slug: "service-portfolio-design",
    title: "Service Portfolio Design",
    summary:
      "Rationalize and redesign service portfolios for measurable outcomes.",
    seo: seo(
      "Service Portfolio Design",
      "Design resilient service portfolios.",
    ),
    heroMedia: img("service-service-portfolio", "Portfolio card matrix", "4:3"),
    tags: ["portfolio", "services"],
    taxonomies: { group: ["consulting"], stage: ["design"] },
    relatedIds: { projects: ["project-civic-grid"], people: ["person-dev"] },
    group: "consulting",
    deliveryMode: "program",
  },
  {
    id: "service-change-enablement",
    slug: "change-enablement",
    title: "Change Enablement",
    summary: "Leadership and team enablement for sustained change adoption.",
    seo: seo(
      "Change Enablement Service",
      "Enable organizational change at scale.",
    ),
    heroMedia: img("service-change-enablement", "Workshop storyboard", "4:3"),
    tags: ["change", "leadership"],
    taxonomies: { group: ["consulting"], stage: ["enablement"] },
    relatedIds: { projects: ["project-orbit-rail"], people: ["person-iris"] },
    group: "consulting",
    deliveryMode: "advisory",
  },
  {
    id: "service-market-activation",
    slug: "market-activation",
    title: "Market Activation",
    summary:
      "Go-to-market orchestration for launches, expansions, and repositioning.",
    seo: seo(
      "Market Activation Service",
      "Activate launches and expansions with confidence.",
    ),
    heroMedia: img(
      "service-market-activation",
      "Launch phase composition",
      "4:3",
    ),
    tags: ["go-to-market", "growth"],
    taxonomies: { group: ["consulting"], stage: ["launch"] },
    relatedIds: {
      projects: ["project-polaris-freight"],
      people: ["person-kofi"],
    },
    group: "consulting",
    deliveryMode: "program",
  },
  {
    id: "service-performance-insight",
    slug: "performance-insight",
    title: "Performance Insight",
    summary:
      "Measurement models and operating dashboards for strategic programs.",
    seo: seo(
      "Performance Insight Service",
      "Measure and improve strategic delivery.",
    ),
    heroMedia: img(
      "service-performance-insight",
      "Dashboard abstraction",
      "4:3",
    ),
    tags: ["analytics", "measurement"],
    taxonomies: { group: ["consulting"], stage: ["measurement"] },
    relatedIds: {
      projects: ["project-rural-signal"],
      people: ["person-kenji"],
    },
    group: "consulting",
    deliveryMode: "advisory",
  },
];

export const innovationPractices: InnovationPractice[] = [
  {
    id: "innovation-foresight-lab",
    slug: "foresight-lab",
    title: "Foresight Lab",
    summary:
      "Scenario planning and strategic foresight for long-horizon decisions.",
    seo: seo(
      "Foresight Lab",
      "Explore future scenarios and strategic implications.",
    ),
    heroMedia: img(
      "innovation-foresight-lab",
      "Speculative horizon visual",
      "16:9",
    ),
    tags: ["foresight", "strategy"],
    taxonomies: { theme: ["Future Readiness"], method: ["Scenario Planning"] },
    relatedIds: {
      articles: ["article-future-portfolio"],
      people: ["person-omar"],
    },
    maturity: "established",
  },
  {
    id: "innovation-prototype-foundry",
    slug: "prototype-foundry",
    title: "Prototype Foundry",
    summary: "Rapid experimentation studio for service and product validation.",
    seo: seo("Prototype Foundry", "Rapidly test and validate strategic bets."),
    heroMedia: img(
      "innovation-prototype-foundry",
      "Prototype bench abstraction",
      "16:9",
    ),
    tags: ["prototyping", "experimentation"],
    taxonomies: { theme: ["Validation"], method: ["Rapid Experimentation"] },
    relatedIds: { projects: ["project-halo-grid"], people: ["person-nadia"] },
    maturity: "emerging",
  },
];

export const people: Person[] = [
  {
    id: "person-amina",
    slug: "amina-doyle",
    title: "Amina Doyle",
    summary: "Principal leading digital transformation programs.",
    seo: seo("Amina Doyle", "Principal at North Axis Studio."),
    heroMedia: img("person-amina", "Portrait placeholder", "3:4"),
    tags: ["transformation", "principal"],
    taxonomies: { discipline: ["Strategy", "Transformation"] },
    relatedIds: {
      projects: ["project-monsoon-loop"],
      services: ["service-transformation-roadmaps"],
    },
    role: "Principal",
    officeId: "office-nyc",
    disciplines: ["Strategy", "Transformation"],
  },
  {
    id: "person-julian",
    slug: "julian-park",
    title: "Julian Park",
    summary: "Design director specializing in service and product ecosystems.",
    seo: seo("Julian Park", "Design Director profile."),
    heroMedia: img("person-julian", "Portrait placeholder", "3:4"),
    tags: ["design", "service"],
    taxonomies: { discipline: ["Experience Design"] },
    relatedIds: {
      projects: ["project-northshore-health"],
      services: ["service-experience-design"],
    },
    role: "Design Director",
    officeId: "office-nyc",
    disciplines: ["Experience Design", "Product"],
  },
  {
    id: "person-soren",
    slug: "soren-birk",
    title: "Soren Birk",
    summary: "Service systems specialist for multi-stakeholder ecosystems.",
    seo: seo("Soren Birk", "Service systems specialist."),
    heroMedia: img("person-soren", "Portrait placeholder", "3:4"),
    tags: ["systems", "service-design"],
    taxonomies: { discipline: ["Systems Design"] },
    relatedIds: {
      projects: ["project-civic-grid"],
      services: ["service-design-ops"],
    },
    role: "Service Systems Lead",
    officeId: "office-cph",
    disciplines: ["Systems Design", "Service Design"],
  },
  {
    id: "person-lina",
    slug: "lina-ahlgren",
    title: "Lina Ahlgren",
    summary: "Identity systems lead across enterprise and cultural brands.",
    seo: seo("Lina Ahlgren", "Identity systems lead."),
    heroMedia: img("person-lina", "Portrait placeholder", "3:4"),
    tags: ["identity", "brand"],
    taxonomies: { discipline: ["Brand Design"] },
    relatedIds: { services: ["service-identity-systems"] },
    role: "Identity Lead",
    officeId: "office-cph",
    disciplines: ["Brand Design", "Typography"],
  },
  {
    id: "person-nadia",
    slug: "nadia-cho",
    title: "Nadia Cho",
    summary: "Transformation consultant focused on regional growth programs.",
    seo: seo("Nadia Cho", "Transformation consultant profile."),
    heroMedia: img("person-nadia", "Portrait placeholder", "3:4"),
    tags: ["consulting", "growth"],
    taxonomies: { discipline: ["Consulting"] },
    relatedIds: {
      projects: ["project-monsoon-loop"],
      innovationPractices: ["innovation-prototype-foundry"],
    },
    role: "Consulting Lead",
    officeId: "office-singapore",
    disciplines: ["Consulting", "Growth"],
  },
  {
    id: "person-kenji",
    slug: "kenji-watanabe",
    title: "Kenji Watanabe",
    summary: "Analytics and performance architect for transformation teams.",
    seo: seo("Kenji Watanabe", "Performance architect profile."),
    heroMedia: img("person-kenji", "Portrait placeholder", "3:4"),
    tags: ["analytics", "performance"],
    taxonomies: { discipline: ["Analytics"] },
    relatedIds: { services: ["service-performance-insight"] },
    role: "Performance Architect",
    officeId: "office-singapore",
    disciplines: ["Analytics", "Data Design"],
  },
  {
    id: "person-kofi",
    slug: "kofi-ndungu",
    title: "Kofi Ndungu",
    summary: "Growth strategist specializing in emerging market ecosystems.",
    seo: seo("Kofi Ndungu", "Growth strategist profile."),
    heroMedia: img("person-kofi", "Portrait placeholder", "3:4"),
    tags: ["growth", "ecosystems"],
    taxonomies: { discipline: ["Growth Strategy"] },
    relatedIds: { projects: ["project-rural-signal"] },
    role: "Growth Strategist",
    officeId: "office-nairobi",
    disciplines: ["Growth", "Ecosystems"],
  },
  {
    id: "person-elena",
    slug: "elena-march",
    title: "Elena March",
    summary:
      "Brand strategist driving complex portfolio repositioning programs.",
    seo: seo("Elena March", "Brand strategist profile."),
    heroMedia: img("person-elena", "Portrait placeholder", "3:4"),
    tags: ["brand", "portfolio"],
    taxonomies: { discipline: ["Brand Strategy"] },
    relatedIds: { projects: ["project-aurora-grid"] },
    role: "Brand Strategist",
    officeId: "office-london",
    disciplines: ["Brand Strategy", "Narrative"],
  },
  {
    id: "person-dev",
    slug: "dev-singh",
    title: "Dev Singh",
    summary: "Public service advisor for policy-to-delivery transformation.",
    seo: seo("Dev Singh", "Public service advisor profile."),
    heroMedia: img("person-dev", "Portrait placeholder", "3:4"),
    tags: ["policy", "public-service"],
    taxonomies: { discipline: ["Policy Design"] },
    relatedIds: { projects: ["project-civic-grid"] },
    role: "Public Service Advisor",
    officeId: "office-toronto",
    disciplines: ["Policy", "Service Design"],
  },
  {
    id: "person-maya",
    slug: "maya-ribeiro",
    title: "Maya Ribeiro",
    summary: "Content and editorial systems designer for product platforms.",
    seo: seo("Maya Ribeiro", "Content systems designer profile."),
    heroMedia: img("person-maya", "Portrait placeholder", "3:4"),
    tags: ["content", "editorial"],
    taxonomies: { discipline: ["Content Design"] },
    relatedIds: { services: ["service-content-design"] },
    role: "Content Design Lead",
    officeId: "office-sao-paulo",
    disciplines: ["Content Design", "Editorial"],
  },
  {
    id: "person-iris",
    slug: "iris-khan",
    title: "Iris Khan",
    summary:
      "Change and capability lead for enterprise transformation rollouts.",
    seo: seo("Iris Khan", "Change lead profile."),
    heroMedia: img("person-iris", "Portrait placeholder", "3:4"),
    tags: ["change", "capability"],
    taxonomies: { discipline: ["Change Enablement"] },
    relatedIds: { services: ["service-change-enablement"] },
    role: "Change Lead",
    officeId: "office-london",
    disciplines: ["Enablement", "Leadership"],
  },
  {
    id: "person-omar",
    slug: "omar-stein",
    title: "Omar Stein",
    summary: "Foresight lead translating uncertainty into strategic options.",
    seo: seo("Omar Stein", "Foresight lead profile."),
    heroMedia: img("person-omar", "Portrait placeholder", "3:4"),
    tags: ["foresight", "strategy"],
    taxonomies: { discipline: ["Foresight"] },
    relatedIds: { innovationPractices: ["innovation-foresight-lab"] },
    role: "Foresight Lead",
    officeId: "office-cph",
    disciplines: ["Foresight", "Scenario Planning"],
  },
];

export const projects: Project[] = [
  {
    id: "project-aurora-grid",
    slug: "aurora-grid-program",
    title: "Aurora Grid Program",
    summary: "Repositioned a multinational energy platform across six regions.",
    seo: seo(
      "Aurora Grid Program",
      "Energy platform transformation case study.",
    ),
    heroMedia: img(
      "project-aurora-grid",
      "Abstract infrastructure geometry",
      "16:9",
    ),
    tags: ["energy", "portfolio"],
    taxonomies: { sector: ["Energy"], region: ["EMEA", "Americas"] },
    relatedIds: {
      services: ["service-brand-architecture"],
      people: ["person-elena"],
    },
    client: "Aurora Utilities",
    year: 2024,
    sector: "Energy",
    status: "Live",
  },
  {
    id: "project-atlas-travel",
    slug: "atlas-travel-ecosystem",
    title: "Atlas Travel Ecosystem",
    summary:
      "Unified booking and loyalty services into one editorial experience.",
    seo: seo(
      "Atlas Travel Ecosystem",
      "Hospitality platform redesign case study.",
    ),
    heroMedia: img(
      "project-atlas-travel",
      "Map-like fluid composition",
      "16:9",
    ),
    tags: ["hospitality", "platform"],
    taxonomies: { sector: ["Hospitality"], region: ["Global"] },
    relatedIds: {
      services: ["service-identity-systems"],
      people: ["person-lina"],
    },
    client: "Atlas Group",
    year: 2025,
    sector: "Hospitality",
    status: "Live",
  },
  {
    id: "project-northshore-health",
    slug: "northshore-health-service",
    title: "Northshore Health Service",
    summary: "Designed a patient-first pathway with clearer care access.",
    seo: seo(
      "Northshore Health Service",
      "Healthcare service transformation case study.",
    ),
    heroMedia: img("project-northshore-health", "Connected care rings", "16:9"),
    tags: ["healthcare", "service"],
    taxonomies: { sector: ["Healthcare"], region: ["Americas"] },
    relatedIds: {
      services: ["service-experience-design"],
      people: ["person-julian"],
    },
    client: "Northshore Health",
    year: 2025,
    sector: "Healthcare",
    status: "Live",
  },
  {
    id: "project-civic-grid",
    slug: "civic-grid-modernization",
    title: "Civic Grid Modernization",
    summary:
      "Modernized public service touchpoints with policy-aligned journeys.",
    seo: seo(
      "Civic Grid Modernization",
      "Public sector modernization case study.",
    ),
    heroMedia: img("project-civic-grid", "Structured civic framework", "16:9"),
    tags: ["public-sector", "policy"],
    taxonomies: { sector: ["Public Sector"], region: ["EMEA", "Americas"] },
    relatedIds: {
      services: ["service-design-ops"],
      people: ["person-soren", "person-dev"],
    },
    client: "Civic Authority",
    year: 2023,
    sector: "Public Sector",
    status: "Live",
  },
  {
    id: "project-monsoon-loop",
    slug: "monsoon-loop-commerce",
    title: "Monsoon Loop Commerce",
    summary: "Scaled omnichannel commerce experiences across APAC markets.",
    seo: seo("Monsoon Loop Commerce", "Retail commerce platform case study."),
    heroMedia: img("project-monsoon-loop", "Retail flow layers", "16:9"),
    tags: ["retail", "commerce"],
    taxonomies: { sector: ["Retail"], region: ["APAC"] },
    relatedIds: {
      services: ["service-transformation-roadmaps"],
      people: ["person-nadia"],
    },
    client: "Monsoon Holdings",
    year: 2024,
    sector: "Retail",
    status: "Live",
  },
  {
    id: "project-rural-signal",
    slug: "rural-signal-network",
    title: "Rural Signal Network",
    summary:
      "Improved access and reliability for distributed service communities.",
    seo: seo("Rural Signal Network", "Distributed network service case study."),
    heroMedia: img("project-rural-signal", "Signal arcs and clusters", "16:9"),
    tags: ["infrastructure", "inclusion"],
    taxonomies: { sector: ["Infrastructure"], region: ["EMEA"] },
    relatedIds: {
      services: ["service-performance-insight"],
      people: ["person-kofi", "person-kenji"],
    },
    client: "SignalNet",
    year: 2022,
    sector: "Infrastructure",
    status: "Live",
  },
  {
    id: "project-verde-finance",
    slug: "verde-finance-growth",
    title: "Verde Finance Growth",
    summary:
      "Designed market activation strategy for regional financial products.",
    seo: seo(
      "Verde Finance Growth",
      "Financial services growth strategy case study.",
    ),
    heroMedia: img(
      "project-verde-finance",
      "Finance dashboard abstraction",
      "16:9",
    ),
    tags: ["finance", "go-to-market"],
    taxonomies: { sector: ["Financial Services"], region: ["Americas"] },
    relatedIds: {
      services: ["service-market-activation"],
      people: ["person-maya"],
    },
    client: "Verde Finance",
    year: 2024,
    sector: "Financial Services",
    status: "Live",
  },
  {
    id: "project-lumen-care",
    slug: "lumen-care-portfolio",
    title: "Lumen Care Portfolio",
    summary:
      "Reframed multi-brand healthcare offers into a coherent ecosystem.",
    seo: seo(
      "Lumen Care Portfolio",
      "Healthcare portfolio architecture case study.",
    ),
    heroMedia: img(
      "project-lumen-care",
      "Layered healthcare card system",
      "16:9",
    ),
    tags: ["healthcare", "brand"],
    taxonomies: { sector: ["Healthcare"], region: ["Global"] },
    relatedIds: {
      services: ["service-brand-architecture"],
      people: ["person-elena"],
    },
    client: "Lumen Care",
    year: 2021,
    sector: "Healthcare",
    status: "Archived",
  },
  {
    id: "project-orbit-rail",
    slug: "orbit-rail-operations",
    title: "Orbit Rail Operations",
    summary: "Built cross-team operating model for service resilience.",
    seo: seo(
      "Orbit Rail Operations",
      "Transportation operations redesign case study.",
    ),
    heroMedia: img("project-orbit-rail", "Transit network motif", "16:9"),
    tags: ["transport", "operations"],
    taxonomies: { sector: ["Transportation"], region: ["Americas"] },
    relatedIds: {
      services: ["service-change-enablement"],
      people: ["person-amina", "person-iris"],
    },
    client: "Orbit Rail",
    year: 2023,
    sector: "Transportation",
    status: "Live",
  },
  {
    id: "project-halo-grid",
    slug: "halo-grid-prototypes",
    title: "Halo Grid Prototypes",
    summary: "Validated service concepts through rapid multi-market pilots.",
    seo: seo("Halo Grid Prototypes", "Innovation prototype case study."),
    heroMedia: img("project-halo-grid", "Prototype matrix pattern", "16:9"),
    tags: ["innovation", "pilots"],
    taxonomies: { sector: ["Utilities"], region: ["APAC", "EMEA"] },
    relatedIds: {
      innovationPractices: ["innovation-prototype-foundry"],
      people: ["person-nadia"],
    },
    client: "Halo Utilities",
    year: 2025,
    sector: "Utilities",
    status: "Live",
  },
  {
    id: "project-polaris-freight",
    slug: "polaris-freight-launch",
    title: "Polaris Freight Launch",
    summary: "Orchestrated cross-region launch for a digital freight platform.",
    seo: seo(
      "Polaris Freight Launch",
      "Freight go-to-market launch case study.",
    ),
    heroMedia: img(
      "project-polaris-freight",
      "Logistics pathway visual",
      "16:9",
    ),
    tags: ["logistics", "launch"],
    taxonomies: { sector: ["Logistics"], region: ["Global"] },
    relatedIds: {
      services: ["service-market-activation"],
      people: ["person-kofi"],
    },
    client: "Polaris Freight",
    year: 2022,
    sector: "Logistics",
    status: "Archived",
  },
  {
    id: "project-cascade-media",
    slug: "cascade-media-platform",
    title: "Cascade Media Platform",
    summary: "Unified publishing workflows and audience pathways.",
    seo: seo(
      "Cascade Media Platform",
      "Media platform transformation case study.",
    ),
    heroMedia: img("project-cascade-media", "Editorial workflow lanes", "16:9"),
    tags: ["media", "platform"],
    taxonomies: { sector: ["Media"], region: ["EMEA"] },
    relatedIds: {
      services: ["service-content-design"],
      people: ["person-maya"],
    },
    client: "Cascade Media",
    year: 2020,
    sector: "Media",
    status: "Archived",
  },
];

export const articles: Article[] = [
  {
    id: "article-clarity-cost",
    slug: "cost-of-unclear-strategy",
    title: "The Cost of Unclear Strategy",
    summary: "Why strategy ambiguity drains delivery velocity.",
    seo: seo(
      "The Cost of Unclear Strategy",
      "A field note on strategy clarity.",
    ),
    heroMedia: img("article-clarity-cost", "Editorial chart motif", "16:9"),
    tags: ["strategy", "leadership"],
    taxonomies: { category: ["Strategy"] },
    relatedIds: {
      services: ["service-transformation-roadmaps"],
      people: ["person-amina"],
    },
    publishedAt: "2026-01-10",
    authorId: "person-amina",
    category: "Strategy",
  },
  {
    id: "article-design-governance",
    slug: "design-governance-at-scale",
    title: "Design Governance at Scale",
    summary: "Practical patterns for distributed design teams.",
    seo: seo(
      "Design Governance at Scale",
      "Governance systems for design organizations.",
    ),
    heroMedia: img(
      "article-design-governance",
      "Grid governance visual",
      "16:9",
    ),
    tags: ["design", "operations"],
    taxonomies: { category: ["Design Ops"] },
    relatedIds: { services: ["service-design-ops"], people: ["person-soren"] },
    publishedAt: "2026-01-21",
    authorId: "person-soren",
    category: "Design Ops",
  },
  {
    id: "article-service-economics",
    slug: "service-economics-baselines",
    title: "Service Economics Baselines",
    summary: "Building realistic baseline metrics before redesign.",
    seo: seo(
      "Service Economics Baselines",
      "How to baseline service economics.",
    ),
    heroMedia: img("article-service-economics", "Data baseline chart", "16:9"),
    tags: ["service", "metrics"],
    taxonomies: { category: ["Consulting"] },
    relatedIds: {
      services: ["service-performance-insight"],
      people: ["person-kenji"],
    },
    publishedAt: "2026-02-02",
    authorId: "person-kenji",
    category: "Consulting",
  },
  {
    id: "article-future-portfolio",
    slug: "future-proof-service-portfolios",
    title: "Future-Proof Service Portfolios",
    summary: "Scenario-led portfolio design for uncertainty.",
    seo: seo(
      "Future-Proof Service Portfolios",
      "Portfolio design in uncertain markets.",
    ),
    heroMedia: img(
      "article-future-portfolio",
      "Scenario tiles composition",
      "16:9",
    ),
    tags: ["foresight", "portfolio"],
    taxonomies: { category: ["Innovation"] },
    relatedIds: {
      innovationPractices: ["innovation-foresight-lab"],
      people: ["person-omar"],
    },
    publishedAt: "2026-02-14",
    authorId: "person-omar",
    category: "Innovation",
  },
  {
    id: "article-content-systems",
    slug: "content-systems-for-product",
    title: "Content Systems for Product Teams",
    summary: "Aligning editorial structure with UI architecture.",
    seo: seo(
      "Content Systems for Product Teams",
      "Editorial systems for product interfaces.",
    ),
    heroMedia: img(
      "article-content-systems",
      "Type and card composition",
      "16:9",
    ),
    tags: ["content", "product"],
    taxonomies: { category: ["Design"] },
    relatedIds: {
      services: ["service-content-design"],
      people: ["person-maya"],
    },
    publishedAt: "2026-02-23",
    authorId: "person-maya",
    category: "Design",
  },
  {
    id: "article-change-fatigue",
    slug: "mitigating-change-fatigue",
    title: "Mitigating Change Fatigue",
    summary: "Signals and interventions for healthier rollouts.",
    seo: seo(
      "Mitigating Change Fatigue",
      "Change management patterns for large organizations.",
    ),
    heroMedia: img(
      "article-change-fatigue",
      "Human-centered change visual",
      "16:9",
    ),
    tags: ["change", "leadership"],
    taxonomies: { category: ["People"] },
    relatedIds: {
      services: ["service-change-enablement"],
      people: ["person-iris"],
    },
    publishedAt: "2026-03-03",
    authorId: "person-iris",
    category: "People",
  },
  {
    id: "article-public-design",
    slug: "public-service-design-playbook",
    title: "Public Service Design Playbook",
    summary: "Improving outcomes by simplifying access pathways.",
    seo: seo(
      "Public Service Design Playbook",
      "Methods for public service design.",
    ),
    heroMedia: img(
      "article-public-design",
      "Public service network visual",
      "16:9",
    ),
    tags: ["public-sector", "service-design"],
    taxonomies: { category: ["Policy"] },
    relatedIds: { projects: ["project-civic-grid"], people: ["person-dev"] },
    publishedAt: "2026-03-17",
    authorId: "person-dev",
    category: "Policy",
  },
  {
    id: "article-market-entry",
    slug: "market-entry-without-friction",
    title: "Market Entry Without Friction",
    summary: "Launch sequencing for regional complexity.",
    seo: seo("Market Entry Without Friction", "Go-to-market sequencing guide."),
    heroMedia: img("article-market-entry", "Launch trajectory visual", "16:9"),
    tags: ["growth", "launch"],
    taxonomies: { category: ["Growth"] },
    relatedIds: {
      services: ["service-market-activation"],
      people: ["person-kofi"],
    },
    publishedAt: "2026-03-28",
    authorId: "person-kofi",
    category: "Growth",
  },
  {
    id: "article-brand-systems",
    slug: "brand-systems-under-pressure",
    title: "Brand Systems Under Pressure",
    summary: "Keeping consistency during rapid expansion.",
    seo: seo(
      "Brand Systems Under Pressure",
      "Brand systems for fast-scaling organizations.",
    ),
    heroMedia: img("article-brand-systems", "Brand system matrix", "16:9"),
    tags: ["brand", "identity"],
    taxonomies: { category: ["Brand"] },
    relatedIds: {
      services: ["service-brand-architecture"],
      people: ["person-elena"],
    },
    publishedAt: "2026-04-01",
    authorId: "person-elena",
    category: "Brand",
  },
  {
    id: "article-platform-resilience",
    slug: "platform-resilience-patterns",
    title: "Platform Resilience Patterns",
    summary: "Foundational architecture decisions that support scale.",
    seo: seo(
      "Platform Resilience Patterns",
      "Resilience patterns for product and service platforms.",
    ),
    heroMedia: img(
      "article-platform-resilience",
      "Platform node pattern",
      "16:9",
    ),
    tags: ["platform", "resilience"],
    taxonomies: { category: ["Technology"] },
    relatedIds: {
      projects: ["project-atlas-travel"],
      people: ["person-julian"],
    },
    publishedAt: "2026-04-06",
    authorId: "person-julian",
    category: "Technology",
  },
];

export const awards: Award[] = Array.from({ length: 20 }).map((_, index) => {
  const year = 2026 - (index % 5);
  const id = `award-${String(index + 1).padStart(2, "0")}`;
  const slug = `editorial-design-award-${index + 1}`;
  return {
    id,
    slug,
    title: `Editorial Design Award ${index + 1}`,
    summary: `Recognition for cross-disciplinary design and consulting excellence in program ${index + 1}.`,
    seo: seo(
      `Editorial Design Award ${index + 1}`,
      `Award profile ${index + 1} from North Axis Studio.`,
    ),
    heroMedia: img(`award-${index + 1}`, "Award medallion placeholder", "4:3"),
    tags: ["recognition", "craft"],
    taxonomies: { category: [index % 2 === 0 ? "Design" : "Consulting"] },
    relatedIds: { projects: [projects[index % projects.length].id] },
    issuer:
      index % 3 === 0 ? "Global Design Forum" : "Strategic Innovation Council",
    year,
    level:
      index % 3 === 0
        ? "winner"
        : index % 3 === 1
          ? "shortlist"
          : "commendation",
  };
});

export const jobs: Job[] = [
  "senior-product-designer",
  "service-designer",
  "brand-strategist",
  "research-lead",
  "transformation-consultant",
  "program-manager",
  "design-operations-lead",
  "content-designer",
  "analytics-consultant",
  "associate-consultant",
  "innovation-producer",
  "people-operations-partner",
].map((slug, index) => ({
  id: `job-${String(index + 1).padStart(2, "0")}`,
  slug,
  title: slug
    .split("-")
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join(" "),
  summary:
    "Role focused on collaborative delivery across strategy, design, and consulting teams.",
  seo: seo(
    `${slug.replace(/-/g, " ")} Role`,
    "Careers opening at North Axis Studio.",
  ),
  heroMedia: img(`job-${index + 1}`, "Job role placeholder", "4:3"),
  tags: ["careers", "studio"],
  taxonomies: { level: [index % 2 === 0 ? "Senior" : "Mid"] },
  relatedIds: {
    offices: [offices[index % offices.length].id],
    testimonials: ["testimonial-01", "testimonial-02"],
  },
  team: index % 2 === 0 ? "Design" : "Consulting",
  officeIds: [
    offices[index % offices.length].id,
    offices[(index + 2) % offices.length].id,
  ],
  employmentType:
    index % 5 === 0 ? "contract" : index % 7 === 0 ? "internship" : "full-time",
}));

export const testimonials: Testimonial[] = [
  {
    id: "testimonial-01",
    slug: "soren-on-craft",
    title: "Soren on craft",
    summary: "Design craft and strategic relevance can and should coexist.",
    seo: seo(
      "Employee Testimonial: Soren",
      "Testimonial from a North Axis employee.",
    ),
    heroMedia: img("testimonial-soren", "Portrait quote card", "4:3"),
    tags: ["culture", "craft"],
    taxonomies: { theme: ["Culture"] },
    relatedIds: { people: ["person-soren"] },
    personId: "person-soren",
    quote:
      "We do not separate elegance from usefulness. The best work is both rigorous and felt.",
  },
  {
    id: "testimonial-02",
    slug: "nadia-on-growth",
    title: "Nadia on growth",
    summary:
      "Global teams create better outcomes when context is shared early.",
    seo: seo(
      "Employee Testimonial: Nadia",
      "Testimonial from a North Axis employee.",
    ),
    heroMedia: img("testimonial-nadia", "Portrait quote card", "4:3"),
    tags: ["culture", "growth"],
    taxonomies: { theme: ["Collaboration"] },
    relatedIds: { people: ["person-nadia"] },
    personId: "person-nadia",
    quote:
      "Growth work is never one office solving for everyone else. We design with local intelligence.",
  },
  {
    id: "testimonial-03",
    slug: "maya-on-editorial-thinking",
    title: "Maya on editorial thinking",
    summary: "Editorial discipline helps teams make better product decisions.",
    seo: seo(
      "Employee Testimonial: Maya",
      "Testimonial from a North Axis employee.",
    ),
    heroMedia: img("testimonial-maya", "Portrait quote card", "4:3"),
    tags: ["editorial", "product"],
    taxonomies: { theme: ["Methods"] },
    relatedIds: { people: ["person-maya"] },
    personId: "person-maya",
    quote:
      "Words are interfaces. Clear language improves trust, speed, and outcomes across the experience.",
  },
  {
    id: "testimonial-04",
    slug: "amina-on-leadership",
    title: "Amina on leadership",
    summary:
      "Leadership alignment is the leverage point in every transformation.",
    seo: seo(
      "Employee Testimonial: Amina",
      "Testimonial from a North Axis employee.",
    ),
    heroMedia: img("testimonial-amina", "Portrait quote card", "4:3"),
    tags: ["leadership", "transformation"],
    taxonomies: { theme: ["Leadership"] },
    relatedIds: { people: ["person-amina"] },
    personId: "person-amina",
    quote:
      "When leaders align on trade-offs, teams move from discussion to delivery much faster.",
  },
];
